spring:
  application:
    name: ms-user
server:
  port: 8081

management:
  endpoint:
    health:
      show-details: always
      show-components: always
  endpoints:
    web:
      exposure:
        include: "health,liquibase,env,loggers,httptrace"
