# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-gradle

name: MS-User CI

on:
  push:
    branches: [ "main" ]
    paths: 
      - 'backend/ms-user/src/**'
  pull_request:
    branches: [ "main" ]
    paths: 
    - 'backend/ms-user/src/**'

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 19
      uses: actions/setup-java@v3
      with:
        java-version: '19'
        distribution: 'temurin'
    - name: Build with Gradle
    - uses: actions/checkout@master
      working-directory: ./backend/ms-user
      run: ./gradlew clean build
    - name: Print something
      run: echo "Hello World!"
